settings:
    lang: en_US
    update-checker: true
    renew-day-cost: 100000
    move-block-cooldown: 3600 #(1 Hours) (-1 to disable)
    claim-day: 30
    #for more than xclaim.max.member.<max>
    default-max-member-in-claim: 3
    #for more than xclaim.max.claim.<max>
    default-max-per-claim: 3
    #if attacker is not attached in the claim
    #can't hit anyone!
    pvp-in-claim: true
    explosions: false
    #when you enter the claim, it sends a alerts message to the screen!
    claim-join-alerts: true
    #ALL = Broadcast all world the claim expired message
    #WORLD = Broadcast claim's world the claim expired message
    claim-expired-broadcast: WORLD
    data-backup-time: 1800 #(30 minutes) (-1 to disable)
    data-save-time: 300 #(5 minutes) (-1 to disable)
    look-chunk-seconds: 15
    claim-create-cooldown: 300 #(5 minutes) (-1 to disable or xclaim.bypass.cooldown)
    #disabled commands in the claim
    #the player cannot run these commands if they are not member of claim
    disabled-commands:
        - "sethome"
        - "tpaccept"
    disabled-worlds:
        - "world_nether"
        - "world_the_end"
    claim-block:
        material: BEDROCK
        display-name: "&r&kx #0BDA51Claim Block! &r&kx"
        lore:
            - "#808080&oPlace the block and create the claim!"
    sounds:
        CLAIM-CREATE:
            enabled: true
            type: ENTITY_PLAYER_LEVELUP
            volume: 0.50
            pitch: 1.0
        OPEN-MANAGAMENT:
            enabled: true
            type: BLOCK_CHEST_OPEN
            volume: 0.50
            pitch: 1.0
        MEMBER-ADD:
            enabled: true
            type: ENTITY_EXPERIENCE_ORB_PICKUP
            volume: 0.75
            pitch: 1.0
        MEMBER-REMOVE:
            enabled: true
            type: BLOCK_AMETHYST_BLOCK_BREAK
            volume: 0.75
            pitch: 1.0
        CLAIM-DELETE:
            enabled: true
            type: ENTITY_ZOMBIE_BREAK_WOODEN_DOOR
            volume: 0.50
            pitch: 1.0
        MOVE-BLOCK:
            enabled: true
            type: ENTITY_EXPERIENCE_ORB_PICKUP
            volume: 0.75
            pitch: 1.0
        RENEW-DAY:
            enabled: true
            type: ENTITY_PLAYER_LEVELUP
            volume: 0.50
            pitch: 1.0