settings:
    lang: en_US
    renew-day-cost: 100000
    move-block-cooldown: 3600 #(1 Hours)
    #if attacker is not attached in the claim
    #can't hit anyone!
    pvp-in-claim: true
    explosions: false
    #when you enter the claim, it sends a alerts message to the screen!
    claim-join-alerts: true
    #ALL = Broadcast all world the claim expired message
    #WORLD = Broadcast claim's world the claim expired message
    claim-expired-broadcast: WORLD
    #disabled commands in the claim
    #the player cannot type these commands if they are not attached in the claim
    disabled-commands:
        - "sethome"
        - "tpaccept"
    disabled-worlds:
        - "world_nether"
        - "world_the_end"
    claim-block:
        material: BEDROCK
        display-name: "#33ffbbClaim block"
        lore:
            - "#f48e9bPlace the block and create the claim!"
gui:
    management-gui:
        member-list:
            gui-title: "#000000Member list!"
            material: TARGETED_HEAD
            display-name: "#115555{player}"
            lore:
                - "#808080Status: {status}"
        member-remove:
            gui-title: "#000000Member remove!"
            material: TARGETED_HEAD
            display-name: "#115555{player}"
            lore:
                - "#808080Status: {status}"
    claim-gui:
        gui-type: DISPENSER
        gui-title: "#000000Claim management"
        #valid for chest only!
        gui-size: 1
        items:
            1:
                material: MAP
                display-name: "#88B04BMember list!"
                lore:
                    - "#115555Click and see!"
                slot: 0
                action: [Member-List]
            2:
                material: ANVIL
                display-name: "#88B04BMember add!"
                lore:
                    - "#115555Click and add!"
                slot: 1
                action: [Member-Add]
            3:
                material: HOPPER
                display-name: "#88B04BMember remove!"
                lore:
                    - "#115555Click and remove!"
                slot: 2
                action: [Member-Remove]
            4:
                material: FIREWORK_ROCKET
                display-name: "#88B04BRenew day!"
                lore:
                    - "#115555Click and renew!"
                slot: 6
                action: [Renew-Day]
            5:
                material: BARRIER
                display-name: "#DD4124Delete claim!"
                lore:
                    - "#115555Click and delete!"
                slot: 7
                action: [Delete-Claim]
            6:
                material: BEDROCK
                display-name: "#45B8ACMove claim block!"
                lore:
                    - "#115555Click and move!"
                slot: 8
                action: [Move-Claim-Block]
            glass1:
                material: GRAY_STAINED_GLASS_PANE
                display-name: " "
                slot: 3
            glass2:
                material: GRAY_STAINED_GLASS_PANE
                display-name: " "
                slot: 4
            glass3:
                material: GRAY_STAINED_GLASS_PANE
                display-name: " "
                slot: 5
claim-hologram:
    settings:
        time-format:
            days: "d"
            hours: "h"
            minutes: "m"
            seconds: "s"
        hologram-height: 3
        hologram-lines:
            - "#EFC050{owner}"
            - ""
            - "#6B5B95Remaining time: &f{remaining-time}"
            - "#6B5B95Team size: &f{team-size}"
            - ""
            - "#F7CAC9Click to manage!"