name: XClaim
authors:
  - mert_out
  - desaxx
version: 1.5.2-fork
api-version: 1.16
main: io.github.mertout.Claim
depends: [Vault, DecentHolograms]
softdepend: [PlaceholderAPI]
commands:
  xclaim:
    description: Main command of XClaim